# Generated by Django 5.2.8 on 2025-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
